{
 "title": "Bind DNS",
 "description": "Bind DNS Service Statistics.\r\n",
 "tags": [
  "dns",
  "bind",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "alias",
    "label": "Host",
    "query": "label_values(bind_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Restarted DNS1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(bind_boot_time_seconds{instance=\"10.77.2.11:9153\"})"
    }
   ]
  },
  {
   "title": "Restarted DNS1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(bind_boot_time_seconds{instance=\"10.77.20.11:9153\"})"
    }
   ]
  },
  {
   "title": "Zone Transfer fails",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bind_zone_transfer_failure_total{instance=~\"$alias\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bind_process_virtual_memory_bytes{instance=~\"$alias\"}",
     "legendFormat": "Virtual {{instance}}"
    },
    {
     "expr": "bind_process_resident_memory_bytes{instance=~\"$alias\"}",
     "legendFormat": "Resident {{instance}}"
    }
   ]
  },
  {
   "title": "Named CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(bind_process_cpu_seconds_total{instance=~\"$alias\"}[120s])"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Incoming Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_queries_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming Request Opcodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_requests_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ opcode }} {{instance}}"
    }
   ]
  },
  {
   "title": "Response Results",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_responses_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ result }} "
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_query_duplicates_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "increase(bind_query_errors_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ error }}"
    },
    {
     "expr": "increase(bind_query_recursions_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "Recursions"
    }
   ]
  },
  { "title": "Resolver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Resolver Cache RR Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bind_resolver_cache_rrsets{instance=~\"$alias\"}",
     "legendFormat": "{{ view }} / {{ type }}"
    }
   ]
  },
  {
   "title": "DNSSEC Validation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_dnssec_validation_errors_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / ValErr"
    },
    {
     "expr": "increase(bind_resolver_dnssec_validation_success_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / {{ result }}"
    }
   ]
  },
  {
   "title": "Resolver Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_queries_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / {{ type }}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_query_errors_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / {{ error }}"
    },
    {
     "expr": "increase(bind_resolver_query_edns0_errors_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / EDNS0"
    },
    {
     "expr": "increase(bind_resolver_query_retries_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / Retry"
    }
   ]
  },
  {
   "title": "Query By Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_query_duration_seconds_bucket{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / {{ le }}"
    }
   ]
  },
  {
   "title": "Resolver Response Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_response_errors_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / {{ error }}"
    },
    {
     "expr": "increase(bind_resolver_response_lame_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / LAME"
    },
    {
     "expr": "increase(bind_resolver_response_mismatch_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / MISMATCH"
    },
    {
     "expr": "increase(bind_resolver_response_truncated_total{instance=~\"$alias\"}[120s])",
     "legendFormat": "{{ view }} / TRUNCATED"
    }
   ]
  }
 ]
}