{
 "title": "VMware ESXi",
 "description": "VMware ESXi single instance graphs.",
 "tags": [
  "prometheus",
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "esxhost",
    "label": "esxhost",
    "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Host CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "CPU SuperMicro",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"10.77.2.249\"}) * 100 / (vmware_host_cpu_max{host_name=~\"10.77.2.249\"})"
    }
   ]
  },
  {
   "title": "CPU Pirat",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"194.14.56.187\"}) * 100 / (vmware_host_cpu_max{host_name=~\"194.14.56.187\"})"
    }
   ]
  },
  {
   "title": "Disk usage SolnaDisk",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ( vmware_datastore_freespace_size{dc_name=~\"Solna\",ds_name =\"NySynNFS2\"} * 100 / vmware_datastore_capacity_size{dc_name=~\"Solna\",ds_name =\"NySynNFS2\"})"
    }
   ]
  },
  {
   "title": "vm Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{host_name=~\"$esxhost\"}/100",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_received_average{dc_name=\"Pirat\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU usage Pirat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "vmware_host_cpu_usage{dc_name=\"Pirat\"}*1000*1000",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage Pirat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{dc_name=\"Pirat\"} * 100) / vmware_host_cpu_max{dc_name=\"Pirat\"} ",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "CPU usage Solna",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none", "label": "MHz" }
   ],
   "targets": [
    {
     "expr": "vmware_host_cpu_usage{dc_name=\"Solna\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage Solna",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{dc_name=\"Solna\"} * 100) / vmware_host_cpu_max{dc_name=\"Solna\"} ",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "vm CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{host_name=~\"$esxhost\"}/100",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "SnapShots",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "vmware_vm_snapshot_timestamp_seconds{host_name=~\"$esxhost\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  }
 ]
}